#!/bin/bash

python3 train_predictor.py --batch 32 --epochs 100 --opt Adadelta --net ConvNet48_333 --lr 0.005

python3 train_predictor.py --batch 32 --epochs 100 --opt ASGD --net ConvNet48_333 --lr 0.005

python3 train_predictor.py --batch 32 --epochs 100 --opt SGD --net ConvNet48_333 --lr 0.005


python3 train_predictor.py --batch 32 --epochs 100 --opt Adadelta --net ConvNet48_Dropout --lr 0.005

python3 train_predictor.py --batch 32 --epochs 100 --opt ASGD --net ConvNet48_Dropout --lr 0.005

python3 train_predictor.py --batch 32 --epochs 100 --opt SGD --net ConvNet48_Dropout --lr 0.005


python3 train_predictor.py --batch 32 --epochs 100 --opt Adadelta --net ConvNet48 --lr 0.005

python3 train_predictor.py --batch 32 --epochs 100 --opt ASGD --net ConvNet48 --lr 0.005

